title: Ace's Blog
author: a3lliott
description: > # this means to ignore newlines until "baseurl:"
  This blog site represents my learning path to advance my skills
  further and become an even better developer.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
